export const REGISTRTAION_START= 'REGISTRATION_START'
export const REGISTRTAION_SUCCESS= 'REGISTRATION_SUCCESS'
export const REGISTRTAION_FAILURE= 'REGISTRATION_FAILURE'



export const USER_LOGIN_START = 'USER_LOGIN_START'
export const USER_LOGIN_SUCCESS = 'USER_LOGIN_SUCCESS'
export const USER_LOGIN_FAILURE = 'USER_LOGIN_FAILURE'